-- Dimension Table: CustomerInfo
CREATE TABLE CustomerInfo (
    CUSTOMER_ID INT PRIMARY KEY,
    CREDIT_SCORE INT NOT NULL,
    FIRST_TIME_HOMEBUYER_FLAG VARCHAR(255) NOT NULL
);

-- Dimension Table: PropertiesInfo
CREATE TABLE PropertiesInfo (
    PROPERTY_ID INT PRIMARY KEY,
    PROPERTY_STATE VARCHAR(255) NOT NULL,
    POSTAL_CODE INT NOT NULL,
    PROPERTY_TYPE VARCHAR(255) NOT NULL
);

-- Fact Table: LoanInfo
CREATE TABLE LoanInfo (
    LOAN_SEQUENCE_NUMBER VARCHAR(255) PRIMARY KEY,
    FIRST_PAYMENT_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    MORTGAGE_INSURANCE_PERCENTAGE INT NOT NULL,
    OCCUPANCY_STATUS VARCHAR(255) NOT NULL,
    ORIGINAL_CLTV INT NOT NULL,
    ORIGINAL_DTI_RATIO INT NOT NULL,
    ORIGINAL_UPB INT NOT NULL,
    ORIGINAL_LTV INT NOT NULL,
    ORIGINAL_INTEREST_RATE DECIMAL NOT NULL,
    CHANNEL VARCHAR(255) NOT NULL,
    ORIGINAL_LOAN_TERM INT NOT NULL,
    NUMBER_OF_BORROWERS INT NOT NULL,
    SELLER_NAME VARCHAR(255) NOT NULL,
    SERVICER_NAME VARCHAR(255) NOT NULL,
    NUMBER_OF_UNITS INT NOT NULL,
    CUSTOMER_ID INT,
	PROPERTY_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CustomerInfo(CUSTOMER_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PropertiesInfo(PROPERTY_ID)
);